### ISSUE TITLE
Compile error: cannot find 'pluginterfaces/vst2.x/aeffect.h'

### ISSUE THREAD

**Issue by simplo** [DBraun/TD-JUCE#10]
Hi all, I followed insttructions trying to build the DLLs.
Firs of all I had many errors because many cpp include files were not found.
I discovered I had to download TDJuce and copy the Juce modules folder in the plugin TD-Juce folder.
Than all includes were found, but now I get this error:
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'pluginterfaces/vst2.x/aeffect.h': No such file or directory	TD-JUCE	C:\Users\paperspace\Documents\TD-JUCE\JuceLibraryCode\juce_audio_processors\format_types\juce_VSTPluginFormat.cpp	49	

I cannot find this file in any folder.
Can you please help me?

**Comment by DBraun** [comment]
I think the issue is that you need to use git to clone this repo. That will use git submodules to download JUCE. Manually downloading JUCE won’t work.

**Comment by simplo** [comment]
Hi, thank you for your reply.
Do you mean to git clone also JUCE?
I used git clone for TD_JUCE.

**Comment by DBraun** [comment]
No just this repo. Can you take a look at this issue? https://github.com/DBraun/TD-JUCE/issues/8 you can also look at the .gitmodules file to find the commit necessary for JUCE_5.

**Comment by simplo** [comment]
You are right, I had to use the complete submodules import commands (I didn't know them).
Thank you!
Now I will test the plugin.
Thank you-

**Comment by DBraun** [comment]
Great!
